# Generated by Django 6.0.4 on 2026-05-12 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'ordering': ['title'], 'verbose_name': 'Категория оборудования', 'verbose_name_plural': 'Категории оборудования'},
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='equipment.equipmentcategory', verbose_name='Родительская категория'),
        ),
    ]
