# Generated by Django 6.0.4 on 2026-04-20 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название типа')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-метка')),
            ],
            options={
                'verbose_name': 'Тип публикации',
                'verbose_name_plural': 'Типы публикаций',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL-метка')),
                ('authors', models.CharField(max_length=500, verbose_name='Авторы')),
                ('abstract', models.TextField(blank=True, verbose_name='Аннотация')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на ресурс')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='PDF файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('authors_employees', models.ManyToManyField(blank=True, to='team.employee', verbose_name='Авторы (сотрудники)')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='research.researchdirection', verbose_name='Направление')),
                ('pub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.publicationtype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
