# Generated by Django 6.0.4 on 2026-06-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.AddField(
            model_name='publication',
            name='external_authors',
            field=models.CharField(blank=True, help_text='Перечислите авторов через запятую, если они не являются сотрудниками лаборатории.', max_length=500, verbose_name='Внешние авторы (не сотрудники)'),
        ),
    ]
