# Generated by Django 6.0.4 on 2026-04-20 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название направления')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL-метка')),
                ('description', models.TextField(verbose_name='Описание направления')),
                ('image', models.ImageField(blank=True, null=True, upload_to='directions/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Направление исследований',
                'verbose_name_plural': 'Направления исследований',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название группы')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL-метка')),
                ('description', models.TextField(verbose_name='Описание группы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='research.researchdirection', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Рабочая группа',
                'verbose_name_plural': 'Рабочие группы',
                'ordering': ['direction', 'title'],
            },
        ),
    ]
